In [1]:
import pandas as pd 
data = pd.read_csv("enjoy.csv")

In [2]:
data.head()

     sky airtemp humidity    wind water forcast enjoysport
0  sunny    warm   normal  strong  warm    same        yes
1  sunny    warm     high  strong  warm    same        yes
2  rainy    cold     high  strong  warm  change         no
3  sunny    warm     high  strong  cool  change        yes

In [3]:
data.tail()

     sky airtemp humidity    wind water forcast enjoysport
0  sunny    warm   normal  strong  warm    same        yes
1  sunny    warm     high  strong  warm    same        yes
2  rainy    cold     high  strong  warm  change         no
3  sunny    warm     high  strong  cool  change        yes

In [4]:
data.describe()

          sky airtemp humidity    wind water forcast enjoysport
count       4       4        4       4     4       4          4
unique      2       2        2       1     2       2          2
top     sunny    warm     high  strong  warm    same        yes
freq        3       3        3       4     3       2          3

In [5]:
X = data.iloc[:, :-1].values
y = data.iloc[:, -1].values

In [6]:
import numpy as np

def find_s(X, y):
    hypothesis = None
    print("Initial Hypothesis:", hypothesis)

    for i in range(len(X)):
        if y[i] == "Yes":
            if hypothesis is None:
                hypothesis = X[i].copy()
            else:
                for j in range(len(hypothesis)):
                    if hypothesis[j] != X[i][j]:
                        hypothesis[j] = "?"

        print(f"\nAfter Training Example {i+1}")
        print(hypothesis)

    return hypothesis


final_hypothesis = find_s(X, y)

print("\nFinal Hypothesis:")
print(final_hypothesis)

Initial Hypothesis: None

After Training Example 1
None

After Training Example 2
None

After Training Example 3
None

After Training Example 4
None

Final Hypothesis:
None

In [7]:
def candidate_elimination(concepts, target):
    specific = concepts[0].copy()
    general = [["?" for i in range(len(specific))]]
    print("\nInitial S:", specific)
    print("Initial G:" , general)
    for i, h in enumerate(concepts):
        if target[i] == "Yes":
            for x in range(len(specific)):
                if h[x] != specific[x]:
                    specific[x] = "?"
        else:
            for x in range(len(specific)):
                if h[x] != specific[x]:
                    general.append(["?" if j != x else specific[x] for j in range(len(specific))])
        print("\nExample", i+1)
        print("S =", specific)
        print("G =", general)
    return specific , general
S, G = candidate_elimination(X,y)
print("\nFinal Specific Boundary")
print(S)
print("\nFinal General Boundary")
for g in G:
    print(g)

Initial S: ['sunny' 'warm' 'normal' 'strong' 'warm' 'same']
Initial G: [['?', '?', '?', '?', '?', '?']]

Example 1
S = ['sunny' 'warm' 'normal' 'strong' 'warm' 'same']
G = [['?', '?', '?', '?', '?', '?']]

Example 2
S = ['sunny' 'warm' 'normal' 'strong' 'warm' 'same']
G = [['?', '?', '?', '?', '?', '?'], ['?', '?', 'normal', '?', '?', '?']]

Example 3
S = ['sunny' 'warm' 'normal' 'strong' 'warm' 'same']
G = [['?', '?', '?', '?', '?', '?'], ['?', '?', 'normal', '?', '?', '?'], ['sunny', '?', '?', '?', '?', '?'], ['?', 'warm', '?', '?', '?', '?'], ['?', '?', 'normal', '?', '?', '?'], ['?', '?', '?', '?', '?', 'same']]

Example 4
S = ['sunny' 'warm' 'normal' 'strong' 'warm' 'same']
G = [['?', '?', '?', '?', '?', '?'], ['?', '?', 'normal', '?', '?', '?'], ['sunny', '?', '?', '?', '?', '?'], ['?', 'warm', '?', '?', '?', '?'], ['?', '?', 'normal', '?', '?', '?'], ['?', '?', '?', '?', '?', 'same'], ['?', '?', 'normal', '?', '?', '?'], ['?', '?', '?', '?', 'warm', '?'], ['?', '?', '?', '?', '?', 'same']]

Final Specific Boundary
['sunny' 'warm' 'normal' 'strong' 'warm' 'same']

Final General Boundary
['?', '?', '?', '?', '?', '?']
['?', '?', 'normal', '?', '?', '?']
['sunny', '?', '?', '?', '?', '?']
['?', 'warm', '?', '?', '?', '?']
['?', '?', 'normal', '?', '?', '?']
['?', '?', '?', '?', '?', 'same']
['?', '?', 'normal', '?', '?', '?']
['?', '?', '?', '?', 'warm', '?']
['?', '?', '?', '?', '?', 'same']